__dataset_size__: '300'
__duration__: '30'
component_eval: 'True'
fitting_mode: fit
param_dict: reviewers/inputs/param_pickle
param_mode: simple
params:
  K: '7'
  decay_time: '0.4'
  fr: '8'
  gSig: '[6, 6]'
  merge_thr: '0.9'
  method_init: greedy_roi
  nb: '2'
  p: '1'
  rf: None
  ssub: '2'
  stride: '10'
  tsub: '2'
