anntype: Keypoint
bodyparts: [Hand, Finger1, Tongue, Joystick1, Joystick2]
dataformat: frames
datasetname: dataset300
finaldatabucket: labeljobfinaldata
fullinstruct: please label
jobname: Examplejobname
numframes2pick: 50
shortintruct: please label
skeleton: [[Hand, Finger1], [Joystick1, Joystick2]]
users: [[Nicktestname, nicholasg101@gmail.com], [Nicktest2, nrg2148@columbia.edu]]
