__dataset_size__: 300
__duration__: 30
atlas_path: reviewers/inputs/supplementary_inputs/atlas.mat
brainmask_name: brainmask
denoised_spatial_name: Uc
denoised_temporal_name: Vc
lambda_init: 1e-06
lambda_step: 1.35
loc_thresh: 80
maxiter_hals: 20
maxiter_lambda: 300
maxrank: 4
min_pixels: 100
r2_thresh: 0.99
