language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt
script:
    - coverage run manage.py test main
    - coverage run manage.py test account
after_success:
    - bash <(curl -s https://codecov.io/bash)
